Web/CapitalSplatsRacquetball.Web/Models/ErrorViewModel.cs
using System;

namespace CapitalSplatsRacquetball.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/CapitalSplatsRacquetball.Web/ViewModels/ContactEmailViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CapitalSplatsRacquetball.Web.ViewModels
{
    public class ContactEmailViewModel
    {
        [Required]
        public string FullName { get; set; }

        [Required]
        public string EmailAddress { get; set; }

        public bool CurrentMember { get; set; }

        public string Comments { get; set; }
    }
}

Web/CapitalSplatsRacquetball.Web/ViewModels/ScoresTableRowViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CapitalSplatsRacquetball.Web.ViewModels
{
    public class ScoresTableRowViewModel
    {
        public int ID { get; set; }
        public string PrettyDate { get; set; }

        public string Location { get; set; }

        public string Player1Name { get; set; }
        
        public string Player2Name { get; set; }

        public int Match1Player1Score { get; set; }

        public int Match1Player2Score { get; set; }

        public int Match2Player1Score { get; set; }

        public int Match2Player2Score { get; set; }
    }
}

Web/CapitalSplatsRacquetball.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CapitalSplatsRacquetball.Web.Models;
using CapitalSplatsRacquetball.Data;
using CapitalSplatsRacquetball.Domain;
using CapitalSplatsRacquetball.Web.ViewModels;
using Microsoft.AspNetCore.Http;
using CapitalSplatsRacquetball.Utility.Email;

namespace CapitalSplatsRacquetball.Web.Controllers
{
    public class HomeController : Controller
    {

        private IHttpContextAccessor _accessor;

        private readonly ILogger<HomeController> _logger;
        private SplatsContext dbContext = new SplatsContext();


        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;

        }

        public IActionResult Index()
        {
            try
            {
                dbContext.Database.EnsureCreated();
       //         AddDummyData();
            }
            catch(Exception e)
            {
                var test = e;
            }

            

            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            var contactViewModel = new ContactEmailViewModel();
            return View(contactViewModel);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Contact(ContactEmailViewModel model)
        {
            if(ModelState.IsValid)
            {

                //attempt to send email and show pop-up to user if successfull
                var recepients = dbContext.RequestEmailRecepients.ToList();
                var contactEmail = new ContactEmail(model.FullName, model.EmailAddress, model.CurrentMember, model.Comments, recepients);
                bool result = contactEmail.Send();
                return Json(new { success = result });
            }
            else
            {
                return Json(new { success = false });
            }
        }

        private void AddDummyData()
        {
            var player1 = new Player{
                FirstName = "James",
                LastName = "Marther",
                Address = "2215 Birther Street Washington, DC 2001",
                Level = Player.SkillLevel.A
            };

            var player2 = new Player
            {
                FirstName = "Helen",
                LastName = "Magruder",
                Address = "252 Connecticut Ave. NW Apt. 509 Washington, DC 2001",
                Level = Player.SkillLevel.A
            };
            dbContext.Players.Add(player1);
            dbContext.Players.Add(player2);
            dbContext.SaveChanges();

            List<Player> players = dbContext.Players.ToList();
            var game1 = new Game
            {
                Date = new DateTime(),
                Player1 = players[0],
                Player2 = players[1],
                MatchesPlayed = 2,
                Location = "JCC"
            };

            dbContext.Games.Add(game1);
            dbContext.SaveChanges();

            List<Game> games = dbContext.Games.ToList();
            var match1 = new GameMatch
            {
                GameId = games[0].Id,
                Player1Score = 5,
                Player2Score = 12
            };
            var match2 = new GameMatch
            {
                GameId = games[0].Id,
                Player1Score = 12,
                Player2Score = 7
            };

            dbContext.Matches.Add(match1);
            dbContext.Matches.Add(match2);
            dbContext.SaveChanges();
        }


        private List<Player> GetPlayers()
        {
            var players = dbContext.Players.ToList();
            return players;
        }
        
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/CapitalSplatsRacquetball.Web/Controllers/ScoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mime;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Threading.Tasks;
using CapitalSplatsRacquetball.Data;
using CapitalSplatsRacquetball.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System.Text.Json;

namespace CapitalSplatsRacquetball.Web.Controllers
{
    public class ScoreController : Controller
    {

        private readonly ILogger<ScoreController> _logger;
        private SplatsContext dbContext = new SplatsContext();

        public ScoreController(ILogger<ScoreController> logger)
        {
            _logger = logger;

        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ContentResult LoadRows()
        {
            var games = dbContext.Games.ToList();
            var matches = dbContext.Matches.ToList();
            var players = dbContext.Players.ToList();
            var items = new List<ScoresTableRowViewModel>();
            foreach( var game in games)
            {
                var player1 = players.Single(p => p.Id == game.Player1.Id);
                var player2 = players.Single(p => p.Id == game.Player2.Id);
                var matchesOfGame = matches.Where(m => m.GameId == game.Id).ToList();
                var row = new ScoresTableRowViewModel
                {
                    ID = game.Id,
                    PrettyDate = game.Date.ToShortDateString(),
                    Location = game.Location,
                    Player1Name = string.Format("{0} {1}", player1.FirstName, player1.LastName),
                    Player2Name = string.Format("{0} {1}", player2.FirstName, player2.LastName),
                    Match1Player1Score = matches.ElementAt(0).Player1Score,
                    Match1Player2Score = matches.ElementAt(0).Player2Score,
                    Match2Player1Score = matches.ElementAt(1).Player1Score,
                    Match2Player2Score = matches.ElementAt(1).Player2Score
                };
                items.Add(row);
            }


            string content = JsonConvert.SerializeObject(new { 
                rows = items,
                total = items.Count
            });

            return new ContentResult() { Content = content, ContentType = "application/json" };

        }
    }
}

Web/CapitalSplatsRacquetball.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<h1 class="text-center">About</h1>
<br />
<br />
<p>
    Capital Splats Racquetball Association (The Capital Splats) was founded in 2010 to establish a friendly place
    for LGBTQ and Allies in the Greater Washington D.C. Metropolitan Area to play racquetball, learn and/or enhance
    racquetball skills, and meet other players.
</p>

<hr />

<p>
    <strong>Racquetball League</strong>

    Our league runs for 4 months and features a season-ending tournament.  There are five divisions:

    <ul>
        <li>A+ > elite/open-level</li>
        <li>A- > expert</li>
        <li>B > advanced</li>
        <li>C > intermediate</li>
        <li>D > beginner</li>
    </ul>
</p>

<p>
    Players within each division play each other
    during the season to be counted toward league standings and may also play any other players in the league for fun.
</p>

<p>
    In addition, the league hosts periodic casual events such as:
    <ul>
        <li>in-season singles tournaments</li>
        <li>doubles tournaments</li>
        <li>open house and meet-and-greet tournaments</li>
    </ul>
</p>

Web/CapitalSplatsRacquetball.Web/Views/Home/Contact.cshtml
@model CapitalSplatsRacquetball.Web.ViewModels.ContactEmailViewModel

@{
    ViewData["Title"] = "Contact";
}

@*This is to alert user that email was successful *@
<div class="alert alert-success" id="SuccessAlert" role="alert" style="display:none;">
    Thanks for reaching out! You should be notified shortly.
</div>


@*This is to alert user that contact form did not work*@
<div class="alert alert-danger" id="FailureAlert" role="alert" style="display:none;">
    There was an error submitting this form. Please try again.
</div>

<h1 class="text-center">Contact</h1>

@using (Html.BeginForm("Contact", "Home", FormMethod.Post, new { @id = "ContactEmailForm" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <label for="FullName">FullName *</label>
        @Html.TextBoxFor(m => m.FullName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.FullName)
    </div>
    <div class="form-group">
        <label for="Email">Email Address *</label>
        @Html.TextBoxFor(m => m.EmailAddress, new { @class = "form-control", type = "email" })
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        @Html.ValidationMessageFor(m => m.EmailAddress)
    </div>
    <div class="form-group">
        <label for="CurrentMember">Current Member *</label>
        <div class="form-check">
            @Html.RadioButton("CurrentMember", true, Model.CurrentMember, new { @class = "form-check-input" })
            <label class="form-check-label" for="CurrentMember">
                Yes
            </label>
        </div>
        <div class="form-check">
            @Html.RadioButton("CurrentMember", false, !Model.CurrentMember, new { @class = "form-check-input" })
            <label class="form-check-label" for="CurrentMember">
                No
            </label>
        </div>
    </div>
    <div class="form-group">
        <label for="Comments">Comments</label>
        <textarea rows="5" id="Comments" name="Comments" class="form-control">@Model.Comments</textarea>
    </div>

    <button type="button" id="btnSubmit" class="btn btn-primary">Submit</button>
}



@section scripts
    {

    <script>
        $('#btnSubmit').click(function (e) {
            e.preventDefault();

            // now trigger the form validation, result is 1 or 0
            let result = $('form').valid(); 

            // submit the form
            $('#ContactEmailForm').ajaxSubmit({
                dataType: "json",
                success: function (json) {
                    if (json.success) {
                        $("#FailureAlert").hide();
                        $("#SuccessAlert").show();
                    }
                    else {
                        $("#SuccessAlert").hide();
                        $("#FailureAlert").show();
                    }
                }
            });
            // return false to prevent normal browser submit and page navigation
             return false;

        });
    </script>


}

Web/CapitalSplatsRacquetball.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Capital Splats Racquetball !</h1>
    <br/><br/>
    <div>
    <p><strong>Capital Splats</strong> is an LGBTQ and Ally non-profit racquetball organization located in the 
    Washington DC metro area. We run a competitive league, one-day racquetball tournaments, 
    teaching clinics, and other events. Our organization features players of all skill level 
    and experience. We welcome newcomers who have never picked up a racquet all the way through 
    experienced tournament players.</p>
        </div>
    <div>
        <p><strong>Capital Splats</strong> is a member of <a href="http://www.teamdc.org/">Team DC</a></p>
    </div>
</div>

Web/CapitalSplatsRacquetball.Web/Views/Score/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Game Scores</h1>


<table id="ScoresTable" class="SortableTable">
    <thead>
        <tr>
            <th data-columnname="PrettyDate">Date</th>
            <th data-columnname="Location">Location</th>
            <th data-columnname="Player1Name">Player 1</th>
            <th data-columnname="Player2Name">Player 2</th>
            <th data-columnname="Match1Player1Score" data-type="numeric">Match1 Player 1 Score</th>
            <th data-columnname="Match1Player2Score" data-type="numeric">Match1 Player 2 Score</th>
            <th data-columnname="Match2Player1Score" data-type="numeric">Match2 Player 1 Score</th>
            <th data-columnname="Match2Player2Score" data-type="numeric">Match2 Player 2 Score</th>
            <th data-columnname="commands" data-formatter="commands" data-sortable="false">Commands</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>



@section scripts
    {

        <script type="text/javascript">
        // Basic grid
           let grid =  $("#ScoresTable").jmkAjaxGridView({
                primaryKeyName: "ID",
                ajaxLoadBindMethod: "/Score/LoadRows",
                orderBy: "Title",
                orderDirection: "ASC",
                rowLoadBinding: function (e, rowLoadBindingEventArgs) {
                    let data = rowLoadBindingEventArgs.data;
                    return {
                        ID: data.ID,
                        PrettyDate: data.PrettyDate,
                        Location: data.Location,
                        Player1Name: data.Player1Name,
                        Player2Name: data.Player2Name,
                        Match1Player1Score: data.Match1Player1Score,
                        Match1Player2Score: data.Match1Player2Score,
                        Match2Player1Score: data.Match2Player1Score,
                        Match2Player2Score: data.Match2Player2Score,
                    };
                },
            });
            
        </script>
}

Web/CapitalSplatsRacquetball.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CapitalSplatsRacquetball.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-theme.css" />
    <link rel="stylesheet" href="~/lib/jquery-bootgrid/dist/css/jquery.bootgrid.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Capital Splats Racquetball</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Score" asp-action="Index">Scores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CapitalSplatsRacquetball.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="http://malsup.github.com/jquery.form.js"></script>    @*used for form ajaxsubmit*@

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://use.fontawesome.com/9cbcc7e7e1.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @*jmk ajax stuff*@
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>
    <script src="~/lib/jmkAjaxStuff/jquery.ba-outside-events.min.js"></script>
    <script src="~/lib/jmkAjaxStuff/jquery.ba-resize.js"></script>
    <script src="~/lib/jmkAjaxStuff/jQuery.jmkTabs-2.0.0.js"></script>
    <script src="~/lib/jmkAjaxStuff/jquery.validate.js"></script>
    <script src="~/lib/jmkAjaxStuff//json2.js"></script>
    <script src="~/lib/jmkAjaxStuff/jquery.jmkAjaxDialog-1.0.0.js"></script>
    <script src="~/lib/jmkAjaxStuff/jquery.jmkAjaxGridView-1.0.0.js"></script>
    <script src="~/lib/jmkAjaxStuff/jQuery.jmkMainMenu-1.1.2.min.js"></script>
    <script src="~/lib/jmkAjaxStuff/jQuery.jmkSelectableTable-1.0.1.js"></script>
    <script src="~/lib/jmkAjaxStuff/jQuery.jmkSortableTable-1.0.0.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>